version: '3.1'

services:
  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: '10'
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: 'false'
      AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE: '127.0.0.1'
    ports:
      - '8081:8081'
      - '10250-10255:10250-10255'